### GET / 
GET http://localhost:5003

### Register a user POST /AUTH/REGISTER
POST http://localhost:5003/auth/register
Content-Type: application/json

{
  "username": "gilgamesh@gmail.com",
  "password": "123456"
}

### Login a user POST /AUTH/LOGIN
POST http://localhost:5003/auth/login
Content-Type: application/json

{
  "username": "gilgamesh@gmail.com",
  "password": "123456"
}

### Fetch all todos GET /TODOS (protected)
GET http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU2MzEwNzg1LCJleHAiOjE3NTYzOTcxODV9.myGQvYE9puupgcxzJJ1q_xWyU6sWhHMmDOM5h1OJrKc

### Creates a new todo POST /TODOS (protected)
POST http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU2MzEwNzg1LCJleHAiOjE3NTYzOTcxODV9.myGQvYE9puupgcxzJJ1q_xWyU6sWhHMmDOM5h1OJrKc
Content-Type: application/json

{
  "task": "Finish coding the project"
}

### Update a todo PUT /TODOS/:ID (protected)
PUT http://localhost:5003/todos/2?page=4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU2MzEwNzg1LCJleHAiOjE3NTYzOTcxODV9.myGQvYE9puupgcxzJJ1q_xWyU6sWhHMmDOM5h1OJrKc
Content-Type: application/json

{
  "completed": 1
}

### Delete a todo DELETE /TODOS/:ID (protected)
DELETE http://localhost:5003/todos/2?page=4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU2MzEwNzg1LCJleHAiOjE3NTYzOTcxODV9.myGQvYE9puupgcxzJJ1q_xWyU6sWhHMmDOM5h1OJrKc
